### ISSUE TITLE
Error al  capturar página de internet

### ISSUE THREAD

**Issue by AntonioCabello** [Six39/SX_auto_screencapture#1]
Colega, al intentar capturar pantalla me aparece el siguiente error: 
ERROR:g1_surface_egl.cc EGL Driver message <critical> EGL_NOT_INITIALIZED. No available renders.

Abre el chrome pero se queda sin hacer nada y de aquí no pasa, instale python 3.7 y volví a decargar el controlador pero no sirve, ¿podrías repararlo?

![error](https://user-images.githubusercontent.com/44346083/47270865-8e2c8500-d537-11e8-962a-85e2c2795cc0.png)

**Comment by Six39** [comment]
No especificas el Sistema Operativo (por la ventana en la imagen parece W7), sin embargo este error parece afectar solo a Windows 7SP1 y Server 2008 R2 SP1. Tienes que instalar actualizaciones que agregan funcionalidades completas o parciales de W8/10 (Direct2D 1.1, DXGI 1.2, etc), para mejorar el rendimiento gráfico.

En este caso necesitamos ampliar el alcance de los componentes gráficos y de imagen, tienes que instalar la Actualización de plataforma para Windows 7/S08R2SP1 y vuelves a intentarlo.

**Descargar Plataforma de W7SP1/Sever 2008 R2SP1:**

[Descargar](https://www.microsoft.com/es-es/download/details.aspx?id=36805)

**Info sobre la Plataforma de actualización:**

[Platform update for Windows 7](https://docs.microsoft.com/es-es/windows/desktop/direct3darticles/platform-update-for-windows-7)
[Plataforma de Actualización W7 - español](https://support.microsoft.com/es-mx/help/2670838/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1)

Saludos

**Comment by AntonioCabello** [comment]
Tienes razón, se realizo la actualización y ha funcionado.
Gracias
